/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_ushow_aac_codec_fdk_AACDecoder */

#ifndef _Included_media_ushow_aac_codec_fdk_AACDecoder
#define _Included_media_ushow_aac_codec_fdk_AACDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     media_ushow_aac_codec_fdk_AACDecoder
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mlingdu_sdk_aac_codec_AACDecoder_decode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
